# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PreProcess": "00_core.ipynb",
         "RecomenderStrategyFactory": "00_core.ipynb",
         "NumericStrategy": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pelayoarbues.github.io/mahoudata/"

git_url = "https://github.com/pelayoarbues/mahoudata/tree/master/"

def custom_doc_links(name): return None
