# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pelayoarbues.github.io/mahou-datathon/"

git_url = "https://github.com/pelayoarbues/mahou-datathon/tree/master/"

def custom_doc_links(name): return None
